server:
    port: 41099
spring:
    datasource:
        url: jdbc:mysql://localhost/pengeluaranku?useSSL=false&serverTimezone=Asia/Jakarta&verifyServerCertificate=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: password
    jpa:
        database: MYSQL
        show-sql: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect